// ==UserScript==
// @name         Defined.fi Auto-Search
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Auto-trigger search when #autosearch parameter present in URL
// @author       Generated by Claude Code
// @match        https://defined.fi/*
// @match        https://www.defined.fi/*
// @grant        none
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';

    console.log('[Defined.fi Auto-Search] Script loaded');

    // Check if autosearch parameter exists in hash
    const hash = window.location.hash;
    if (!hash.startsWith('#autosearch=')) {
        console.log('[Defined.fi Auto-Search] No autosearch parameter found');
        return;
    }

    // Extract the address from the hash
    const address = hash.split('=')[1];
    console.log('[Defined.fi Auto-Search] Address to search:', address);

    // Remove the hash from URL so it doesn't persist
    history.replaceState(null, '', window.location.pathname + window.location.search);

    // Wait for page to be ready and search component to load
    let attempts = 0;
    const maxAttempts = 100; // 10 seconds maximum wait
    const checkInterval = 100; // Check every 100ms

    const checkAndTriggerSearch = setInterval(() => {
        attempts++;

        // Safety timeout: stop checking after 10 seconds
        if (attempts >= maxAttempts) {
            console.error('[Defined.fi Auto-Search] Timeout: Could not find search elements');
            clearInterval(checkAndTriggerSearch);
            return;
        }

        // Strategy 1: Try to find and click search trigger button
        // Common selectors for search buttons/triggers on SPAs
        const searchTriggers = [
            '[data-search-trigger]',
            '[aria-label*="Search" i]',
            '[aria-label*="search" i]',
            'button[aria-label*="Search" i]',
            '[data-testid*="search" i]',
            '.search-trigger',
            '.search-button'
        ];

        let searchTrigger = null;
        for (const selector of searchTriggers) {
            searchTrigger = document.querySelector(selector);
            if (searchTrigger) {
                console.log('[Defined.fi Auto-Search] Found search trigger:', selector);
                break;
            }
        }

        // Strategy 2: Check for Ctrl+K keyboard shortcut listener
        // If no button found, simulate Ctrl+K (common pattern for search)
        if (!searchTrigger) {
            // Try simulating Ctrl+K which is mentioned in the requirements
            const ctrlKEvent = new KeyboardEvent('keydown', {
                key: 'k',
                code: 'KeyK',
                keyCode: 75,
                which: 75,
                ctrlKey: true,
                bubbles: true,
                cancelable: true
            });
            document.dispatchEvent(ctrlKEvent);
            console.log('[Defined.fi Auto-Search] Dispatched Ctrl+K event');
        } else {
            // Click the search trigger
            searchTrigger.click();
            console.log('[Defined.fi Auto-Search] Clicked search trigger');
        }

        // Wait a bit for search input to appear
        setTimeout(() => {
            // Try to find the search input field
            const searchInputSelectors = [
                'input[type="search"]',
                'input[placeholder*="Search" i]',
                'input[placeholder*="search" i]',
                'input[aria-label*="Search" i]',
                'input[aria-label*="search" i]',
                'input[data-testid*="search" i]',
                '.search-input',
                '[role="searchbox"]',
                'input[type="text"]'  // Fallback to any text input
            ];

            let searchInput = null;
            for (const selector of searchInputSelectors) {
                searchInput = document.querySelector(selector);
                if (searchInput && searchInput.offsetParent !== null) {  // Check if visible
                    console.log('[Defined.fi Auto-Search] Found search input:', selector);
                    break;
                }
            }

            if (searchInput) {
                clearInterval(checkAndTriggerSearch);
                console.log('[Defined.fi Auto-Search] Found search input, filling with address');

                // Focus the input
                searchInput.focus();

                // Set the value
                searchInput.value = address;

                // Trigger input events to ensure the app detects the change
                searchInput.dispatchEvent(new Event('input', { bubbles: true }));
                searchInput.dispatchEvent(new Event('change', { bubbles: true }));

                console.log('[Defined.fi Auto-Search] Filled input with:', address);

                // Wait a bit for suggestions/results to load, then submit
                setTimeout(() => {
                    // Strategy 1: Try to submit via form
                    const form = searchInput.closest('form');
                    if (form) {
                        console.log('[Defined.fi Auto-Search] Submitting via form');
                        form.submit();
                        return;
                    }

                    // Strategy 2: Press Enter key
                    console.log('[Defined.fi Auto-Search] Submitting via Enter key');
                    const enterEvent = new KeyboardEvent('keydown', {
                        key: 'Enter',
                        code: 'Enter',
                        keyCode: 13,
                        which: 13,
                        bubbles: true,
                        cancelable: true
                    });
                    searchInput.dispatchEvent(enterEvent);

                    // Also try keypress and keyup for compatibility
                    searchInput.dispatchEvent(new KeyboardEvent('keypress', {
                        key: 'Enter',
                        code: 'Enter',
                        keyCode: 13,
                        which: 13,
                        bubbles: true
                    }));
                    searchInput.dispatchEvent(new KeyboardEvent('keyup', {
                        key: 'Enter',
                        code: 'Enter',
                        keyCode: 13,
                        which: 13,
                        bubbles: true
                    }));

                    console.log('[Defined.fi Auto-Search] Search completed');
                }, 300);  // Wait 300ms for autocomplete to load
            }
        }, 200);  // Wait 200ms after clicking trigger

    }, checkInterval);

})();