// ==UserScript==
// @name         Defined.fi Auto-Search
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Auto-trigger search when #autosearch parameter present in URL
// @author       Generated by Claude Code
// @match        https://defined.fi/*
// @match        https://www.defined.fi/*
// @grant        none
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';

    console.log('[Defined.fi Auto-Search] Script loaded');

    // Check if autosearch parameter exists in hash
    const hash = window.location.hash;
    if (!hash.startsWith('#autosearch=')) {
        console.log('[Defined.fi Auto-Search] No autosearch parameter found');
        return;
    }

    // Extract the address from the hash
    const address = hash.split('=')[1];
    console.log('[Defined.fi Auto-Search] Address to search:', address);

    // Remove the hash from URL so it doesn't persist
    history.replaceState(null, '', window.location.pathname + window.location.search);

    // Wait for page to be fully loaded, then trigger search
    let ctrlKSent = false;

    function trySearch() {
        // Only send Ctrl+K once
        if (!ctrlKSent) {
            console.log('[Defined.fi Auto-Search] Dispatching Ctrl+K event');
            const ctrlKEvent = new KeyboardEvent('keydown', {
                key: 'k',
                code: 'KeyK',
                keyCode: 75,
                which: 75,
                ctrlKey: true,
                bubbles: true,
                cancelable: true
            });
            document.dispatchEvent(ctrlKEvent);
            ctrlKSent = true;
        }

        // Wait for search modal to open and input to appear
        setTimeout(() => {
            const searchInputSelectors = [
                'input[type="search"]',
                'input[placeholder*="Search" i]',
                'input[placeholder*="search" i]',
                'input[aria-label*="Search" i]',
                'input[aria-label*="search" i]',
                'input[data-testid*="search" i]',
                '.search-input',
                '[role="searchbox"]',
                'input[type="text"]' // Fallback to any text input
            ];

            let searchInput = null;
            for (const selector of searchInputSelectors) {
                searchInput = document.querySelector(selector);
                if (searchInput && searchInput.offsetParent !== null) { // Check if visible
                    console.log('[Defined.fi Auto-Search] Found search input:', selector);
                    break;
                }
            }

            if (searchInput) {
                console.log('[Defined.fi Auto-Search] Filling search input with address');

                // Focus the input
                searchInput.focus();

                // Set the value using native setter to trigger React
                const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
                nativeInputValueSetter.call(searchInput, address);

                // Trigger React's synthetic events
                const inputEvent = new Event('input', { bubbles: true });
                searchInput.dispatchEvent(inputEvent);

                console.log('[Defined.fi Auto-Search] Filled input with:', address);

                // Wait for React to process the input, then press Enter
                setTimeout(() => {
                    console.log('[Defined.fi Auto-Search] Pressing Enter to search');

                    searchInput.dispatchEvent(new KeyboardEvent('keydown', {
                        key: 'Enter',
                        code: 'Enter',
                        keyCode: 13,
                        which: 13,
                        bubbles: true,
                        cancelable: true
                    }));

                    console.log('[Defined.fi Auto-Search] Search completed');
                }, 500); // Give React time to process the input
            } else {
                console.log('[Defined.fi Auto-Search] Search input not found');
            }
        }, 400); // Wait 400ms for modal to open after Ctrl+K
    }

    // Wait for page to be ready, then try once
    if (document.readyState === 'complete') {
        setTimeout(trySearch, 800); // Wait 800ms for React to fully initialize
    } else {
        window.addEventListener('load', () => {
            setTimeout(trySearch, 800); // Wait 800ms after load
        });
    }

})();