#!/usr/bin/env python3
"""
============================================================================
Solana Address Monitoring Service
============================================================================
Description: Local Flask service that receives Solana addresses from
             AutoHotkey script and stores them for Telegram monitoring
Author: Generated by Claude Code
Version: 1.0 (Phase 1 - MVP)
============================================================================
"""

from flask import Flask, request, jsonify, render_template
from datetime import datetime
import json
import os
import re

app = Flask(__name__)

# Configuration
DATA_FILE = "monitored_addresses.json"
DEFAULT_THRESHOLD = 100  # Default SOL threshold for notifications

# In-memory storage (backed by JSON file)
monitored_addresses = {}


def load_addresses():
    """Load monitored addresses from JSON file"""
    global monitored_addresses
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, 'r') as f:
                monitored_addresses = json.load(f)
            print(f"✓ Loaded {len(monitored_addresses)} monitored addresses from {DATA_FILE}")
        except Exception as e:
            print(f"⚠ Error loading addresses: {e}")
            monitored_addresses = {}
    else:
        monitored_addresses = {}
        print(f"⚠ No existing data file found. Starting fresh.")


def save_addresses():
    """Save monitored addresses to JSON file"""
    try:
        with open(DATA_FILE, 'w') as f:
            json.dump(monitored_addresses, f, indent=2)
        return True
    except Exception as e:
        print(f"⚠ Error saving addresses: {e}")
        return False


def is_valid_solana_address(address):
    """
    Validate Solana address format
    - Must be 32-44 characters
    - Must only contain base58 characters (no 0, O, I, l)
    """
    if not address or not isinstance(address, str):
        return False

    # Length check
    if len(address) < 32 or len(address) > 44:
        return False

    # Base58 character check (excludes 0, O, I, l)
    base58_pattern = r'^[1-9A-HJ-NP-Za-km-z]+$'
    if not re.match(base58_pattern, address):
        return False

    return True


@app.route('/register', methods=['POST'])
def register_address():
    """
    Register a new Solana address for monitoring

    Expected JSON payload:
    {
        "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "timestamp": "20250101120000"  # optional
    }
    """
    try:
        data = request.get_json()

        if not data:
            return jsonify({"error": "No JSON data provided"}), 400

        address = data.get('address', '').strip()

        # Validate address
        if not is_valid_solana_address(address):
            return jsonify({"error": "Invalid Solana address format"}), 400

        # Check if already registered
        if address in monitored_addresses:
            return jsonify({
                "status": "already_registered",
                "message": f"Address already being monitored",
                "address": address,
                "registered_at": monitored_addresses[address]['registered_at']
            }), 200

        # Add new address with optional note
        note = data.get('note', '').strip() if data.get('note') else None

        monitored_addresses[address] = {
            "address": address,
            "registered_at": datetime.now().isoformat(),
            "threshold": DEFAULT_THRESHOLD,
            "total_notifications": 0,
            "last_notification": None,
            "note": note
        }

        # Save to file
        if save_addresses():
            print(f"✓ Registered new address: {address}")
            return jsonify({
                "status": "success",
                "message": "Address registered for monitoring",
                "address": address,
                "threshold": DEFAULT_THRESHOLD,
                "total_monitored": len(monitored_addresses)
            }), 201
        else:
            return jsonify({"error": "Failed to save address"}), 500

    except Exception as e:
        print(f"⚠ Error in /register: {e}")
        return jsonify({"error": str(e)}), 500


@app.route('/addresses', methods=['GET'])
def list_addresses():
    """List all monitored addresses"""
    return jsonify({
        "total": len(monitored_addresses),
        "addresses": list(monitored_addresses.values())
    }), 200


@app.route('/address/<address>', methods=['GET'])
def get_address(address):
    """Get details for a specific address"""
    if address in monitored_addresses:
        return jsonify(monitored_addresses[address]), 200
    else:
        return jsonify({"error": "Address not found"}), 404


@app.route('/address/<address>', methods=['DELETE'])
def remove_address(address):
    """Remove an address from monitoring"""
    if address in monitored_addresses:
        del monitored_addresses[address]
        save_addresses()
        print(f"✓ Removed address: {address}")
        return jsonify({
            "status": "success",
            "message": "Address removed from monitoring",
            "address": address
        }), 200
    else:
        return jsonify({"error": "Address not found"}), 404


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({
        "status": "running",
        "monitored_addresses": len(monitored_addresses),
        "timestamp": datetime.now().isoformat()
    }), 200


@app.route('/address/<address>/note', methods=['PUT'])
def update_note(address):
    """Update note/tag for an address"""
    if address not in monitored_addresses:
        return jsonify({"error": "Address not found"}), 404

    try:
        data = request.get_json()
        note = data.get('note', '').strip() if data.get('note') else None

        monitored_addresses[address]['note'] = note
        save_addresses()
        print(f"✓ Updated note for address: {address}")

        return jsonify({
            "status": "success",
            "message": "Note updated successfully",
            "address": address,
            "note": note
        }), 200

    except Exception as e:
        print(f"⚠ Error updating note: {e}")
        return jsonify({"error": str(e)}), 500


@app.route('/import', methods=['POST'])
def import_addresses():
    """Import addresses from backup file"""
    try:
        data = request.get_json()
        imported = data.get('addresses', [])

        if not isinstance(imported, list):
            return jsonify({"error": "Invalid import format"}), 400

        added = 0
        skipped = 0

        for addr_data in imported:
            if isinstance(addr_data, dict):
                address = addr_data.get('address')
                if address and is_valid_solana_address(address):
                    if address not in monitored_addresses:
                        monitored_addresses[address] = {
                            "address": address,
                            "registered_at": addr_data.get('registered_at', datetime.now().isoformat()),
                            "threshold": addr_data.get('threshold', DEFAULT_THRESHOLD),
                            "total_notifications": addr_data.get('total_notifications', 0),
                            "last_notification": addr_data.get('last_notification'),
                            "note": addr_data.get('note')
                        }
                        added += 1
                    else:
                        skipped += 1

        save_addresses()
        print(f"✓ Imported {added} addresses ({skipped} skipped as duplicates)")

        return jsonify({
            "status": "success",
            "message": f"Imported {added} addresses ({skipped} duplicates skipped)",
            "added": added,
            "skipped": skipped,
            "total": len(monitored_addresses)
        }), 200

    except Exception as e:
        print(f"⚠ Error importing addresses: {e}")
        return jsonify({"error": str(e)}), 500


@app.route('/clear', methods=['POST'])
def clear_all():
    """Clear all monitored addresses (use with caution!)"""
    global monitored_addresses
    count = len(monitored_addresses)
    monitored_addresses = {}
    save_addresses()
    print(f"⚠ Cleared all {count} monitored addresses")
    return jsonify({
        "status": "success",
        "message": f"Cleared {count} addresses",
        "total_monitored": 0
    }), 200


@app.route('/')
def dashboard():
    """Serve web dashboard"""
    return render_template('dashboard.html')


if __name__ == '__main__':
    print("=" * 70)
    print("Solana Address Monitoring Service")
    print("=" * 70)
    print(f"Starting Flask server on http://localhost:5001")
    print(f"Data file: {DATA_FILE}")
    print(f"Default threshold: {DEFAULT_THRESHOLD} SOL")
    print("-" * 70)

    # Load existing addresses
    load_addresses()

    print("-" * 70)
    print("Available endpoints:")
    print("  GET    /                      - Web Dashboard")
    print("  POST   /register              - Register new address")
    print("  GET    /addresses             - List all addresses")
    print("  GET    /address/<addr>        - Get address details")
    print("  DELETE /address/<addr>        - Remove address")
    print("  PUT    /address/<addr>/note   - Update address note")
    print("  POST   /import                - Import addresses from backup")
    print("  GET    /health                - Health check")
    print("  POST   /clear                 - Clear all addresses")
    print("-" * 70)
    print("\n📊 Open http://localhost:5001 in your browser to access the dashboard")
    print("Press Ctrl+C to stop the server")
    print("=" * 70)
    print()

    # Run server
    app.run(host='localhost', port=5001, debug=False)