/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - API information
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint with WebSocket connection count
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Debug Mode
         * @description Get current debug mode status
         */
        get: operations["get_debug_mode_api_debug_mode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Debug Config
         * @description Get debug configuration for frontend
         */
        get: operations["get_debug_config_api_debug_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Api Settings
         * @description Get current API settings
         *
         *     Returns:
         *         API settings dictionary
         */
        get: operations["get_api_settings_api_settings_get"];
        put?: never;
        /**
         * Update Api Settings
         * @description Update API settings
         *
         *     Args:
         *         payload: Settings to update
         *
         *     Returns:
         *         Updated settings
         */
        post: operations["update_api_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Address
         * @description Register a wallet address for monitoring
         *
         *     Args:
         *         payload: Address and optional note
         *
         *     Returns:
         *         Registration status and details
         */
        post: operations["register_address_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Addresses
         * @description Get list of all monitored addresses
         *
         *     Returns:
         *         Total count and list of addresses
         */
        get: operations["list_addresses_addresses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Address
         * @description Get details of a specific monitored address
         *
         *     Args:
         *         address: Solana wallet address
         *
         *     Returns:
         *         Address details
         */
        get: operations["get_address_address__address__get"];
        put?: never;
        post?: never;
        /**
         * Delete Address
         * @description Remove an address from monitoring
         *
         *     Args:
         *         address: Solana wallet address
         *
         *     Returns:
         *         Deletion status
         */
        delete: operations["delete_address_address__address__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/{address}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Address Note
         * @description Update the note for a monitored address
         *
         *     Args:
         *         address: Solana wallet address
         *         payload: New note text
         *
         *     Returns:
         *         Update status
         */
        put: operations["update_address_note_address__address__note_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Addresses
         * @description Import multiple addresses at once
         *
         *     Args:
         *         payload: List of address entries
         *
         *     Returns:
         *         Import summary
         */
        post: operations["import_addresses_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Addresses
         * @description Clear all monitored addresses
         *
         *     Returns:
         *         Clearing status
         */
        post: operations["clear_addresses_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tokens History
         * @description Get all non-deleted tokens with wallet counts (with caching)
         */
        get: operations["get_tokens_history_api_tokens_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deleted Tokens
         * @description Get all soft-deleted tokens
         */
        get: operations["get_deleted_tokens_api_tokens_trash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token By Id
         * @description Get token details with wallets and axiom export
         */
        get: operations["get_token_by_id_api_tokens__token_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft Delete Token
         * @description Soft delete a token (move to trash)
         */
        delete: operations["soft_delete_token_api_tokens__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{token_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Analysis History
         * @description Get analysis history for a specific token
         */
        get: operations["get_token_analysis_history_api_tokens__token_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{token_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Token
         * @description Restore a soft-deleted token
         */
        post: operations["restore_token_api_tokens__token_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{token_id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Permanent Delete Token
         * @description Permanently delete a token and all associated data
         */
        delete: operations["permanent_delete_token_api_tokens__token_id__permanent_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Token
         * @description Analyze a token to find early bidders (queues job)
         */
        post: operations["analyze_token_analyze_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get analysis job status and results
         */
        get: operations["get_analysis_analysis__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analyses
         * @description List analysis jobs and completed tokens
         */
        get: operations["list_analyses_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{job_id}/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Analysis Csv
         * @description Export analysis results as CSV
         */
        get: operations["export_analysis_csv_analysis__job_id__csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/{job_id}/axiom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Axiom Export
         * @description Download Axiom wallet tracker JSON
         */
        get: operations["download_axiom_export_analysis__job_id__axiom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multi-token-wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Multi Early Buyer Wallets
         * @description Get wallets that appear in multiple tokens
         */
        get: operations["get_multi_early_buyer_wallets_multi_token_wallets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/refresh-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Wallet Balances
         * @description Refresh wallet balances for multiple wallets (ASYNC)
         */
        post: operations["refresh_wallet_balances_wallets_refresh_balances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{wallet_address}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wallet Tags
         * @description Get tags for a wallet
         */
        get: operations["get_wallet_tags_wallets__wallet_address__tags_get"];
        put?: never;
        /**
         * Add Wallet Tag
         * @description Add a tag to a wallet
         */
        post: operations["add_wallet_tag_wallets__wallet_address__tags_post"];
        /**
         * Remove Wallet Tag
         * @description Remove a tag from a wallet
         */
        delete: operations["remove_wallet_tag_wallets__wallet_address__tags_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Tags
         * @description Get all unique tags
         */
        get: operations["get_all_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/codex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Codex
         * @description Get all wallets with tags (Codex)
         */
        get: operations["get_codex_codex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/batch-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Batch Wallet Tags
         * @description Get tags for multiple wallets in one query
         */
        post: operations["get_batch_wallet_tags_wallets_batch_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tag}/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wallets By Tag
         * @description Get all wallets with a specific tag
         */
        get: operations["get_wallets_by_tag_tags__tag__wallets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Webhook
         * @description Create a Helius webhook for monitoring token wallets
         */
        post: operations["create_webhook_webhooks_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhooks
         * @description List all webhooks for this API key
         */
        get: operations["list_webhooks_webhooks_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Webhook Details
         * @description Get details of a specific webhook
         */
        get: operations["get_webhook_details_webhooks__webhook_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Webhook
         * @description Delete a webhook
         */
        delete: operations["delete_webhook_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook Callback
         * @description Receive webhook notifications from Helius
         */
        post: operations["webhook_callback_webhooks_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notify/analysis_complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify Analysis Complete
         * @description HTTP endpoint to trigger analysis complete notifications
         */
        post: operations["notify_analysis_complete_notify_analysis_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notify/analysis_start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify Analysis Start
         * @description HTTP endpoint to trigger analysis start notifications
         */
        post: operations["notify_analysis_start_notify_analysis_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddTagRequest */
        AddTagRequest: {
            /** Tag */
            tag: string;
            /**
             * Is Kol
             * @default false
             */
            is_kol: boolean;
        };
        /** AddressNoteRequest */
        AddressNoteRequest: {
            /** Note */
            note?: string | null;
        };
        /**
         * AnalysisCompleteNotification
         * @description Notification payload for analysis completion
         */
        AnalysisCompleteNotification: {
            /** Job Id */
            job_id: string;
            /** Token Name */
            token_name: string;
            /** Token Symbol */
            token_symbol: string;
            /** Acronym */
            acronym: string;
            /** Wallets Found */
            wallets_found: number;
            /** Token Id */
            token_id: number;
        };
        /** AnalysisHistory */
        AnalysisHistory: {
            /** Token Id */
            token_id: number;
            /** Total Runs */
            total_runs: number;
            /** Runs */
            runs: components["schemas"]["AnalysisRun"][];
        };
        /** AnalysisRun */
        AnalysisRun: {
            /** Id */
            id: number;
            /** Analysis Timestamp */
            analysis_timestamp: string;
            /** Wallets Found */
            wallets_found: number;
            /** Credits Used */
            credits_used: number;
            /** Wallets */
            wallets: {
                [key: string]: unknown;
            }[];
        };
        /**
         * AnalysisSettings
         * @description API settings for token analysis
         */
        AnalysisSettings: {
            /**
             * Transactionlimit
             * @default 500
             */
            transactionLimit: number;
            /**
             * Minusdfilter
             * @default 50
             */
            minUsdFilter: number;
            /**
             * Walletcount
             * @default 10
             */
            walletCount: number;
            /**
             * Apiratedelay
             * @default 100
             */
            apiRateDelay: number;
            /**
             * Maxcreditsperanalysis
             * @default 1000
             */
            maxCreditsPerAnalysis: number;
            /**
             * Maxretries
             * @default 3
             */
            maxRetries: number;
        };
        /**
         * AnalysisStartNotification
         * @description Notification payload for analysis start
         */
        AnalysisStartNotification: {
            /** Job Id */
            job_id: string;
            /** Token Name */
            token_name: string;
            /** Token Symbol */
            token_symbol: string;
        };
        /**
         * AnalyzeTokenRequest
         * @description Request model for token analysis
         */
        AnalyzeTokenRequest: {
            /**
             * Address
             * @description Solana token address
             */
            address: string;
            api_settings?: components["schemas"]["AnalysisSettings"] | null;
            /** Min Usd */
            min_usd?: number | null;
            /**
             * Time Window Hours
             * @default 999999
             */
            time_window_hours: number;
        };
        /** BatchTagsRequest */
        BatchTagsRequest: {
            /** Addresses */
            addresses: string[];
        };
        /** CodexResponse */
        CodexResponse: {
            /** Wallets */
            wallets: components["schemas"]["CodexWallet"][];
        };
        /** CodexWallet */
        CodexWallet: {
            /** Wallet Address */
            wallet_address: string;
            /** Tags */
            tags: components["schemas"]["WalletTag"][];
        };
        /** CreateWebhookRequest */
        CreateWebhookRequest: {
            /** Token Id */
            token_id: number;
            /** Webhook Url */
            webhook_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportAddressEntry */
        ImportAddressEntry: {
            /** Address */
            address: string;
            /** Registered At */
            registered_at?: string | null;
            /** Threshold */
            threshold?: number | null;
            /** Total Notifications */
            total_notifications?: number | null;
            /** Last Notification */
            last_notification?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ImportAddressesRequest */
        ImportAddressesRequest: {
            /** Addresses */
            addresses: components["schemas"]["ImportAddressEntry"][];
        };
        /**
         * MessageResponse
         * @description Simple message response
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MultiTokenWallet */
        MultiTokenWallet: {
            /** Wallet Address */
            wallet_address: string;
            /** Token Count */
            token_count: number;
            /** Token Names */
            token_names: string[];
            /** Token Addresses */
            token_addresses: string[];
            /** Token Ids */
            token_ids: number[];
            /** Wallet Balance Usd */
            wallet_balance_usd: number | null;
        };
        /** MultiTokenWalletsResponse */
        MultiTokenWalletsResponse: {
            /** Total */
            total: number;
            /** Wallets */
            wallets: components["schemas"]["MultiTokenWallet"][];
        };
        /** RefreshBalancesRequest */
        RefreshBalancesRequest: {
            /** Wallet Addresses */
            wallet_addresses: string[];
        };
        /** RefreshBalancesResponse */
        RefreshBalancesResponse: {
            /** Message */
            message: string;
            /** Results */
            results: components["schemas"]["RefreshBalancesResult"][];
            /** Total Wallets */
            total_wallets: number;
            /** Successful */
            successful: number;
            /** Api Credits Used */
            api_credits_used: number;
        };
        /** RefreshBalancesResult */
        RefreshBalancesResult: {
            /** Wallet Address */
            wallet_address: string;
            /** Balance Usd */
            balance_usd: number | null;
            /** Success */
            success: boolean;
        };
        /** RegisterAddressRequest */
        RegisterAddressRequest: {
            /** Address */
            address: string;
            /** Note */
            note?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** RemoveTagRequest */
        RemoveTagRequest: {
            /** Tag */
            tag: string;
        };
        /** TagsResponse */
        TagsResponse: {
            /** Tags */
            tags: string[];
        };
        /** Token */
        Token: {
            /** Id */
            id: number;
            /** Token Address */
            token_address: string;
            /** Token Name */
            token_name: string | null;
            /** Token Symbol */
            token_symbol: string | null;
            /** Acronym */
            acronym: string;
            /** Analysis Timestamp */
            analysis_timestamp: string;
            /** First Buy Timestamp */
            first_buy_timestamp: string | null;
            /** Wallets Found */
            wallets_found: number;
            /** Credits Used */
            credits_used?: number | null;
            /** Last Analysis Credits */
            last_analysis_credits?: number | null;
            /** Wallet Addresses */
            wallet_addresses?: string[] | null;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * TokenDetail
         * @description Token with wallet details and axiom data
         */
        TokenDetail: {
            /** Id */
            id: number;
            /** Token Address */
            token_address: string;
            /** Token Name */
            token_name: string | null;
            /** Token Symbol */
            token_symbol: string | null;
            /** Acronym */
            acronym: string;
            /** Analysis Timestamp */
            analysis_timestamp: string;
            /** First Buy Timestamp */
            first_buy_timestamp: string | null;
            /** Wallets Found */
            wallets_found: number;
            /** Credits Used */
            credits_used?: number | null;
            /** Last Analysis Credits */
            last_analysis_credits?: number | null;
            /** Deleted At */
            deleted_at?: string | null;
            /** Wallets */
            wallets: {
                [key: string]: unknown;
            }[];
            /** Axiom Json */
            axiom_json: unknown[];
        };
        /** TokensResponse */
        TokensResponse: {
            /** Total */
            total: number;
            /** Total Wallets */
            total_wallets: number;
            /** Tokens */
            tokens: components["schemas"]["Token"][];
        };
        /** UpdateSettingsRequest */
        UpdateSettingsRequest: {
            /** Transactionlimit */
            transactionLimit?: number | null;
            /** Minusdfilter */
            minUsdFilter?: number | null;
            /** Walletcount */
            walletCount?: number | null;
            /** Apiratedelay */
            apiRateDelay?: number | null;
            /** Maxcreditsperanalysis */
            maxCreditsPerAnalysis?: number | null;
            /** Maxretries */
            maxRetries?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalletTag */
        WalletTag: {
            /** Tag */
            tag: string;
            /** Is Kol */
            is_kol: boolean;
        };
        /** WalletTagsResponse */
        WalletTagsResponse: {
            /** Tags */
            tags: components["schemas"]["WalletTag"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_debug_mode_api_debug_mode_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_debug_config_api_debug_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_api_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_api_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_address_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAddressRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_addresses_addresses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_address_address__address__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_address_address__address__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_address_note_address__address__note_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_addresses_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportAddressesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_addresses_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_tokens_history_api_tokens_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
        };
    };
    get_deleted_tokens_api_tokens_trash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensResponse"];
                };
            };
        };
    };
    get_token_by_id_api_tokens__token_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_token_api_tokens__token_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_token_analysis_history_api_tokens__token_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_token_api_tokens__token_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    permanent_delete_token_api_tokens__token_id__permanent_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_token_analyze_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analysis__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_analysis_get: {
        parameters: {
            query?: {
                search?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_analysis_csv_analysis__job_id__csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_axiom_export_analysis__job_id__axiom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_multi_early_buyer_wallets_multi_token_wallets_get: {
        parameters: {
            query?: {
                min_tokens?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiTokenWalletsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_wallet_balances_wallets_refresh_balances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshBalancesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshBalancesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallet_tags_wallets__wallet_address__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_wallet_tag_wallets__wallet_address__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_wallet_tag_wallets__wallet_address__tags_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wallet_address: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveTagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
    get_codex_codex_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexResponse"];
                };
            };
        };
    };
    get_batch_wallet_tags_wallets_batch_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wallets_by_tag_tags__tag__wallets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_webhook_webhooks_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks_webhooks_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_webhook_details_webhooks__webhook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_callback_webhooks_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    notify_analysis_complete_notify_analysis_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisCompleteNotification"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notify_analysis_start_notify_analysis_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisStartNotification"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
